# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: ge-pvc
#   namespace: ge-dev
#   labels:
#     app: ge-config
# spec:
#   accessModes:
#     - ReadWriteMany  
#   storageClassName: ge-secure-premium # Azure storage class
#   resources:
#     requests:
#       storage: 3Gi

apiVersion: v1
kind: PersistentVolume
metadata:
  name: ge-pv-dev
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
    - dir_mode=0777
    - file_mode=0777
    - uid=0
    - gid=0
    - mfsymlinks
    - nobrl
  csi:
    driver: file.csi.azure.com
    volumeHandle: PlayFromHome#gepvcstorage888#ge-fileshare
    volumeAttributes:
      shareName: ge-fileshare
    nodeStageSecretRef:
      name: azure-storage-account-secret
      namespace: ge-dev
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ge-pvc
  namespace: ge-dev
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  volumeName: ge-pv-dev

