apiVersion: v1
kind: ServiceAccount
metadata:
  name: restart-sa
  namespace: ge-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: restart-role
  namespace: ge-dev
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch", "list", "watch"]

  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: restart-role-binding
  namespace: ge-dev
subjects:
  - kind: ServiceAccount
    name: restart-sa
    namespace: ge-dev
roleRef:
  kind: Role
  name: restart-role
  apiGroup: rbac.authorization.k8s.io