# -----------------------------------------------------------
# GE Service: Services Only (1-5)
# -----------------------------------------------------------

apiVersion: v1
kind: Service
metadata:
  name: ge-service-1
  namespace: ge-dev
  labels:
    app: ge-service-1
    shard: "1"
spec:
  type: ClusterIP
  selector:
    app: ge-service
    shard: "1"
  ports:
  - protocol: TCP
    name: http
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ge-service-2
  namespace: ge-dev
  labels:
    app: ge-service-2
    shard: "2"
spec:
  type: LoadBalancer
  selector:
    app: ge-service
    shard: "2"
  ports:
  - protocol: TCP
    # name: http
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ge-service-3
  namespace: ge-dev
  labels:
    app: ge-service-3
    shard: "3"
spec:
  type: ClusterIP
  selector:
    app: ge-service
    shard: "3"
  ports:
  - protocol: TCP
    name: http
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ge-service-4
  namespace: ge-dev
  labels:
    app: ge-service-4
    shard: "4"
spec:
  type: ClusterIP
  selector:
    app: ge-service
    shard: "4"
  ports:
  - protocol: TCP
    name: http
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ge-service-5
  namespace: ge-dev
  labels:
    app: ge-service-5
    shard: "5"
spec:
  type: ClusterIP
  selector:
    app: ge-service
    shard: "5"
  ports:
  - protocol: TCP
    name: http
    port: 8080
    targetPort: 8080