apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ge-web-hpa
spec:
  
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ge-web-deployment 
  
  
  minReplicas: 1 
  maxReplicas: 5 
  
  # Define the scaling metric 
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        #CPU usage across all Pods hits 70%, HPA scales out.
        averageUtilization: 70