apiVersion: v1
kind: Service
metadata:
  name: ge-web
  namespace: ge-dev
spec:
  type: ClusterIP # External IP - ingress-nginx
  selector:
    app: ge-web
  ports:
  - protocol: TCP
    port: 80     
    targetPort: 8080