apiVersion: v1
kind: Secret
metadata:
  name: sentry-secrets
  namespace: ge-dev
type: Opaque
stringData:
  SENTRY_DSN: "https://da79a941d16df1b8c8a42dca79f6afef@o4506922190635008.ingest.us.sentry.io/4510783002050560"
